version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
      - npm install time
      - export BUCKET=devops-poc-artifact
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputtemplate.yaml  
  discard-paths: yes
