Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  StageName:
    Type: String
    Description: ApiGateway Stage Name
    Default: test
  LambdaCodeUri:
    Type: String
    Description: Lambda Code Uri
    Default: app/
  LambdaHandler:
    Type: String
    Description: lambda handler
    Default: server.handler
  RunTime:
    Type: String
    Description: LambdaRuntime
    Default: nodejs10.x
  ApiGateWayName:
    Type: String
    Description: ApiGateway name
    Default: TEST-API
Resources:
  BasicAWSApiGateway:
    Type: 'AWS::Serverless::Api'
    Properties:
      Name: !Ref ApiGateWayName
      StageName: !Ref StageName
  LambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: app/
      Handler: server.handler
      Runtime: nodejs10.x
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            RestApiId: !Ref BasicAWSApiGateway
            Method: get
            Path: /
